# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mahaoyuan/HDDT

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mahaoyuan/HDDT

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mahaoyuan/HDDT/CMakeFiles /home/mahaoyuan/HDDT//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mahaoyuan/HDDT/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named hddt_cuda_shared

# Build rule for target.
hddt_cuda_shared: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hddt_cuda_shared
.PHONY : hddt_cuda_shared

# fast build rule for target.
hddt_cuda_shared/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_cuda_shared.dir/build.make CMakeFiles/hddt_cuda_shared.dir/build
.PHONY : hddt_cuda_shared/fast

#=============================================================================
# Target rules for targets named hddt_shared_lib

# Build rule for target.
hddt_shared_lib: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hddt_shared_lib
.PHONY : hddt_shared_lib

# fast build rule for target.
hddt_shared_lib/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/build
.PHONY : hddt_shared_lib/fast

#=============================================================================
# Target rules for targets named train_cnn

# Build rule for target.
train_cnn: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 train_cnn
.PHONY : train_cnn

# fast build rule for target.
train_cnn/fast:
	$(MAKE) $(MAKESILENT) -f apps/train_cnn/CMakeFiles/train_cnn.dir/build.make apps/train_cnn/CMakeFiles/train_cnn.dir/build
.PHONY : train_cnn/fast

#=============================================================================
# Target rules for targets named simple_inference

# Build rule for target.
simple_inference: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 simple_inference
.PHONY : simple_inference

# fast build rule for target.
simple_inference/fast:
	$(MAKE) $(MAKESILENT) -f apps/simple_inference/CMakeFiles/simple_inference.dir/build.make apps/simple_inference/CMakeFiles/simple_inference.dir/build
.PHONY : simple_inference/fast

#=============================================================================
# Target rules for targets named torch_app

# Build rule for target.
torch_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 torch_app
.PHONY : torch_app

# fast build rule for target.
torch_app/fast:
	$(MAKE) $(MAKESILENT) -f apps/torch_app/CMakeFiles/torch_app.dir/build.make apps/torch_app/CMakeFiles/torch_app.dir/build
.PHONY : torch_app/fast

#=============================================================================
# Target rules for targets named rdma_server

# Build rule for target.
rdma_server: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rdma_server
.PHONY : rdma_server

# fast build rule for target.
rdma_server/fast:
	$(MAKE) $(MAKESILENT) -f apps/rdma_app/CMakeFiles/rdma_server.dir/build.make apps/rdma_app/CMakeFiles/rdma_server.dir/build
.PHONY : rdma_server/fast

#=============================================================================
# Target rules for targets named rdma_client

# Build rule for target.
rdma_client: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 rdma_client
.PHONY : rdma_client

# fast build rule for target.
rdma_client/fast:
	$(MAKE) $(MAKESILENT) -f apps/rdma_app/CMakeFiles/rdma_client.dir/build.make apps/rdma_app/CMakeFiles/rdma_client.dir/build
.PHONY : rdma_client/fast

#=============================================================================
# Target rules for targets named mem

# Build rule for target.
mem: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 mem
.PHONY : mem

# fast build rule for target.
mem/fast:
	$(MAKE) $(MAKESILENT) -f apps/rdma_app/CMakeFiles/mem.dir/build.make apps/rdma_app/CMakeFiles/mem.dir/build
.PHONY : mem/fast

#=============================================================================
# Target rules for targets named coll_app

# Build rule for target.
coll_app: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 coll_app
.PHONY : coll_app

# fast build rule for target.
coll_app/fast:
	$(MAKE) $(MAKESILENT) -f apps/coll_app/CMakeFiles/coll_app.dir/build.make apps/coll_app/CMakeFiles/coll_app.dir/build
.PHONY : coll_app/fast

#=============================================================================
# Target rules for targets named HDDT_test

# Build rule for target.
HDDT_test: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 HDDT_test
.PHONY : HDDT_test

# fast build rule for target.
HDDT_test/fast:
	$(MAKE) $(MAKESILENT) -f tests/CMakeFiles/HDDT_test.dir/build.make tests/CMakeFiles/HDDT_test.dir/build
.PHONY : HDDT_test/fast

src/driver.o: src/driver.cpp.o
.PHONY : src/driver.o

# target to build an object file
src/driver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/driver.cpp.o
.PHONY : src/driver.cpp.o

src/driver.i: src/driver.cpp.i
.PHONY : src/driver.i

# target to preprocess a source file
src/driver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/driver.cpp.i
.PHONY : src/driver.cpp.i

src/driver.s: src/driver.cpp.s
.PHONY : src/driver.s

# target to generate assembly for a file
src/driver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/driver.cpp.s
.PHONY : src/driver.cpp.s

src/mem/cuda_memory.o: src/mem/cuda_memory.cpp.o
.PHONY : src/mem/cuda_memory.o

# target to build an object file
src/mem/cuda_memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/cuda_memory.cpp.o
.PHONY : src/mem/cuda_memory.cpp.o

src/mem/cuda_memory.i: src/mem/cuda_memory.cpp.i
.PHONY : src/mem/cuda_memory.i

# target to preprocess a source file
src/mem/cuda_memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/cuda_memory.cpp.i
.PHONY : src/mem/cuda_memory.cpp.i

src/mem/cuda_memory.s: src/mem/cuda_memory.cpp.s
.PHONY : src/mem/cuda_memory.s

# target to generate assembly for a file
src/mem/cuda_memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/cuda_memory.cpp.s
.PHONY : src/mem/cuda_memory.cpp.s

src/mem/hddt_memory.o: src/mem/hddt_memory.cpp.o
.PHONY : src/mem/hddt_memory.o

# target to build an object file
src/mem/hddt_memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/hddt_memory.cpp.o
.PHONY : src/mem/hddt_memory.cpp.o

src/mem/hddt_memory.i: src/mem/hddt_memory.cpp.i
.PHONY : src/mem/hddt_memory.i

# target to preprocess a source file
src/mem/hddt_memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/hddt_memory.cpp.i
.PHONY : src/mem/hddt_memory.cpp.i

src/mem/hddt_memory.s: src/mem/hddt_memory.cpp.s
.PHONY : src/mem/hddt_memory.s

# target to generate assembly for a file
src/mem/hddt_memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/hddt_memory.cpp.s
.PHONY : src/mem/hddt_memory.cpp.s

src/mem/host_memory.o: src/mem/host_memory.cpp.o
.PHONY : src/mem/host_memory.o

# target to build an object file
src/mem/host_memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/host_memory.cpp.o
.PHONY : src/mem/host_memory.cpp.o

src/mem/host_memory.i: src/mem/host_memory.cpp.i
.PHONY : src/mem/host_memory.i

# target to preprocess a source file
src/mem/host_memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/host_memory.cpp.i
.PHONY : src/mem/host_memory.cpp.i

src/mem/host_memory.s: src/mem/host_memory.cpp.s
.PHONY : src/mem/host_memory.s

# target to generate assembly for a file
src/mem/host_memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/host_memory.cpp.s
.PHONY : src/mem/host_memory.cpp.s

src/mem/neuware_memory.o: src/mem/neuware_memory.cpp.o
.PHONY : src/mem/neuware_memory.o

# target to build an object file
src/mem/neuware_memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/neuware_memory.cpp.o
.PHONY : src/mem/neuware_memory.cpp.o

src/mem/neuware_memory.i: src/mem/neuware_memory.cpp.i
.PHONY : src/mem/neuware_memory.i

# target to preprocess a source file
src/mem/neuware_memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/neuware_memory.cpp.i
.PHONY : src/mem/neuware_memory.cpp.i

src/mem/neuware_memory.s: src/mem/neuware_memory.cpp.s
.PHONY : src/mem/neuware_memory.s

# target to generate assembly for a file
src/mem/neuware_memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/neuware_memory.cpp.s
.PHONY : src/mem/neuware_memory.cpp.s

src/mem/rocm_memory.o: src/mem/rocm_memory.cpp.o
.PHONY : src/mem/rocm_memory.o

# target to build an object file
src/mem/rocm_memory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/rocm_memory.cpp.o
.PHONY : src/mem/rocm_memory.cpp.o

src/mem/rocm_memory.i: src/mem/rocm_memory.cpp.i
.PHONY : src/mem/rocm_memory.i

# target to preprocess a source file
src/mem/rocm_memory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/rocm_memory.cpp.i
.PHONY : src/mem/rocm_memory.cpp.i

src/mem/rocm_memory.s: src/mem/rocm_memory.cpp.s
.PHONY : src/mem/rocm_memory.s

# target to generate assembly for a file
src/mem/rocm_memory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/mem/rocm_memory.cpp.s
.PHONY : src/mem/rocm_memory.cpp.s

src/net/cuda/net_cuda_reduce.o: src/net/cuda/net_cuda_reduce.cu.o
.PHONY : src/net/cuda/net_cuda_reduce.o

# target to build an object file
src/net/cuda/net_cuda_reduce.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_cuda_shared.dir/build.make CMakeFiles/hddt_cuda_shared.dir/src/net/cuda/net_cuda_reduce.cu.o
.PHONY : src/net/cuda/net_cuda_reduce.cu.o

src/net/cuda/net_cuda_reduce.i: src/net/cuda/net_cuda_reduce.cu.i
.PHONY : src/net/cuda/net_cuda_reduce.i

# target to preprocess a source file
src/net/cuda/net_cuda_reduce.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_cuda_shared.dir/build.make CMakeFiles/hddt_cuda_shared.dir/src/net/cuda/net_cuda_reduce.cu.i
.PHONY : src/net/cuda/net_cuda_reduce.cu.i

src/net/cuda/net_cuda_reduce.s: src/net/cuda/net_cuda_reduce.cu.s
.PHONY : src/net/cuda/net_cuda_reduce.s

# target to generate assembly for a file
src/net/cuda/net_cuda_reduce.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_cuda_shared.dir/build.make CMakeFiles/hddt_cuda_shared.dir/src/net/cuda/net_cuda_reduce.cu.s
.PHONY : src/net/cuda/net_cuda_reduce.cu.s

src/net/net.o: src/net/net.cpp.o
.PHONY : src/net/net.o

# target to build an object file
src/net/net.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/net/net.cpp.o
.PHONY : src/net/net.cpp.o

src/net/net.i: src/net/net.cpp.i
.PHONY : src/net/net.i

# target to preprocess a source file
src/net/net.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/net/net.cpp.i
.PHONY : src/net/net.cpp.i

src/net/net.s: src/net/net.cpp.s
.PHONY : src/net/net.s

# target to generate assembly for a file
src/net/net.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/net/net.cpp.s
.PHONY : src/net/net.cpp.s

src/net/rdma_communictor.o: src/net/rdma_communictor.cpp.o
.PHONY : src/net/rdma_communictor.o

# target to build an object file
src/net/rdma_communictor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/net/rdma_communictor.cpp.o
.PHONY : src/net/rdma_communictor.cpp.o

src/net/rdma_communictor.i: src/net/rdma_communictor.cpp.i
.PHONY : src/net/rdma_communictor.i

# target to preprocess a source file
src/net/rdma_communictor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/net/rdma_communictor.cpp.i
.PHONY : src/net/rdma_communictor.cpp.i

src/net/rdma_communictor.s: src/net/rdma_communictor.cpp.s
.PHONY : src/net/rdma_communictor.s

# target to generate assembly for a file
src/net/rdma_communictor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/net/rdma_communictor.cpp.s
.PHONY : src/net/rdma_communictor.cpp.s

src/net/tcp_communictor.o: src/net/tcp_communictor.cpp.o
.PHONY : src/net/tcp_communictor.o

# target to build an object file
src/net/tcp_communictor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/net/tcp_communictor.cpp.o
.PHONY : src/net/tcp_communictor.cpp.o

src/net/tcp_communictor.i: src/net/tcp_communictor.cpp.i
.PHONY : src/net/tcp_communictor.i

# target to preprocess a source file
src/net/tcp_communictor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/net/tcp_communictor.cpp.i
.PHONY : src/net/tcp_communictor.cpp.i

src/net/tcp_communictor.s: src/net/tcp_communictor.cpp.s
.PHONY : src/net/tcp_communictor.s

# target to generate assembly for a file
src/net/tcp_communictor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/net/tcp_communictor.cpp.s
.PHONY : src/net/tcp_communictor.cpp.s

src/nn/cuda/nn_cuda_cnn.o: src/nn/cuda/nn_cuda_cnn.cu.o
.PHONY : src/nn/cuda/nn_cuda_cnn.o

# target to build an object file
src/nn/cuda/nn_cuda_cnn.cu.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_cuda_shared.dir/build.make CMakeFiles/hddt_cuda_shared.dir/src/nn/cuda/nn_cuda_cnn.cu.o
.PHONY : src/nn/cuda/nn_cuda_cnn.cu.o

src/nn/cuda/nn_cuda_cnn.i: src/nn/cuda/nn_cuda_cnn.cu.i
.PHONY : src/nn/cuda/nn_cuda_cnn.i

# target to preprocess a source file
src/nn/cuda/nn_cuda_cnn.cu.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_cuda_shared.dir/build.make CMakeFiles/hddt_cuda_shared.dir/src/nn/cuda/nn_cuda_cnn.cu.i
.PHONY : src/nn/cuda/nn_cuda_cnn.cu.i

src/nn/cuda/nn_cuda_cnn.s: src/nn/cuda/nn_cuda_cnn.cu.s
.PHONY : src/nn/cuda/nn_cuda_cnn.s

# target to generate assembly for a file
src/nn/cuda/nn_cuda_cnn.cu.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_cuda_shared.dir/build.make CMakeFiles/hddt_cuda_shared.dir/src/nn/cuda/nn_cuda_cnn.cu.s
.PHONY : src/nn/cuda/nn_cuda_cnn.cu.s

src/nn/nn.o: src/nn/nn.cpp.o
.PHONY : src/nn/nn.o

# target to build an object file
src/nn/nn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/nn/nn.cpp.o
.PHONY : src/nn/nn.cpp.o

src/nn/nn.i: src/nn/nn.cpp.i
.PHONY : src/nn/nn.i

# target to preprocess a source file
src/nn/nn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/nn/nn.cpp.i
.PHONY : src/nn/nn.cpp.i

src/nn/nn.s: src/nn/nn.cpp.s
.PHONY : src/nn/nn.s

# target to generate assembly for a file
src/nn/nn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/nn/nn.cpp.s
.PHONY : src/nn/nn.cpp.s

src/test_py.o: src/test_py.cpp.o
.PHONY : src/test_py.o

# target to build an object file
src/test_py.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/test_py.cpp.o
.PHONY : src/test_py.cpp.o

src/test_py.i: src/test_py.cpp.i
.PHONY : src/test_py.i

# target to preprocess a source file
src/test_py.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/test_py.cpp.i
.PHONY : src/test_py.cpp.i

src/test_py.s: src/test_py.cpp.s
.PHONY : src/test_py.s

# target to generate assembly for a file
src/test_py.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hddt_shared_lib.dir/build.make CMakeFiles/hddt_shared_lib.dir/src/test_py.cpp.s
.PHONY : src/test_py.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... HDDT_test"
	@echo "... coll_app"
	@echo "... hddt_cuda_shared"
	@echo "... hddt_shared_lib"
	@echo "... mem"
	@echo "... rdma_client"
	@echo "... rdma_server"
	@echo "... simple_inference"
	@echo "... torch_app"
	@echo "... train_cnn"
	@echo "... src/driver.o"
	@echo "... src/driver.i"
	@echo "... src/driver.s"
	@echo "... src/mem/cuda_memory.o"
	@echo "... src/mem/cuda_memory.i"
	@echo "... src/mem/cuda_memory.s"
	@echo "... src/mem/hddt_memory.o"
	@echo "... src/mem/hddt_memory.i"
	@echo "... src/mem/hddt_memory.s"
	@echo "... src/mem/host_memory.o"
	@echo "... src/mem/host_memory.i"
	@echo "... src/mem/host_memory.s"
	@echo "... src/mem/neuware_memory.o"
	@echo "... src/mem/neuware_memory.i"
	@echo "... src/mem/neuware_memory.s"
	@echo "... src/mem/rocm_memory.o"
	@echo "... src/mem/rocm_memory.i"
	@echo "... src/mem/rocm_memory.s"
	@echo "... src/net/cuda/net_cuda_reduce.o"
	@echo "... src/net/cuda/net_cuda_reduce.i"
	@echo "... src/net/cuda/net_cuda_reduce.s"
	@echo "... src/net/net.o"
	@echo "... src/net/net.i"
	@echo "... src/net/net.s"
	@echo "... src/net/rdma_communictor.o"
	@echo "... src/net/rdma_communictor.i"
	@echo "... src/net/rdma_communictor.s"
	@echo "... src/net/tcp_communictor.o"
	@echo "... src/net/tcp_communictor.i"
	@echo "... src/net/tcp_communictor.s"
	@echo "... src/nn/cuda/nn_cuda_cnn.o"
	@echo "... src/nn/cuda/nn_cuda_cnn.i"
	@echo "... src/nn/cuda/nn_cuda_cnn.s"
	@echo "... src/nn/nn.o"
	@echo "... src/nn/nn.i"
	@echo "... src/nn/nn.s"
	@echo "... src/test_py.o"
	@echo "... src/test_py.i"
	@echo "... src/test_py.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

